/* ============================================================
   Шпаргалка Кодоквеста — справочник по командам, которые забываются.

   Открывается ПОВЕРХ любого экрана (кнопка «Шпаргалка» в шапке), а не
   отдельной страницей. Причина простая: чаще всего она нужна прямо посреди
   урока, а уход со страницы урока стирает написанный код. Оверлей ничего
   не стирает.

   Устройство записи:
     id      — свой, для поиска и тестов
     sig     — как это пишется
     what    — что делает, одной фразой
     code    — короткий пример, 1–4 строки
     lesson  — id урока, где это объясняли (по нему считается «пройдено»)
     data    — необязательно: файлы рядом с примером, { "имя.txt": "текст" }.
               Нужны записям про open() и csv: без файла такой пример упал бы,
               а команды эти забываются чаще всех остальных

   Вывод примера НЕ хранится: он считается движком в момент показа. Значит,
   он не может разойтись с тем, что ребёнок получит у себя.

   Правила для примеров (их проверяют тесты):
     - пример обязан запускаться и что-то печатать (tests/lessons.js);
     - пример обязан совпадать с настоящим python3 (tests/content-vs-python.js);
     - lesson обязан быть настоящим id урока из curriculum.js;
     - никакой черепашки и ввода с клавиатуры. Файлы можно, но только через
       поле data: и тренажёр, и python3 в проверке получают их одинаково.
       Случайность можно: пример со случайным числом честно показывает разное.
   ============================================================ */
window.CHEATSHEET = [
{
  group: "Вывод и текст",
  items: [
    { id:"print", sig:"print(a, b)", lesson:"print-first",
      what:"печатает значения на экран, разделяя пробелом",
      code:'print("Привет", 2026)' },
    { id:"print-sep", sig:"print(..., sep=, end=)", lesson:"print-first",
      what:"меняет разделитель между значениями и хвост строки",
      code:'print("а", "б", "в", sep="-")\nprint("без переноса", end="!")' },
    { id:"fstring", sig:'f"текст {значение}"', lesson:"fstrings",
      what:"вставляет значение прямо внутрь строки",
      code:'имя = "Аня"\nочки = 42\nprint(f"{имя} набрала {очки}")' },
    { id:"fstring-width", sig:'f"{значение:6}"', lesson:"fstrings",
      what:"выравнивает по ширине — так строки встают в столбик",
      code:'for слово in ["кот", "бегемот"]:\n    print(f"|{слово:10}|")' },
    { id:"fstring-fixed", sig:'f"{число:.2f}"', lesson:"fn-multi",
      what:"два знака после запятой. Двоеточие в f-строке начинает формат",
      code:'цена = 1234.5678\nprint(f"{цена:.2f}")\nprint(f"{7:.2f}")' },
    { id:"str-plus", sig:'"а" + "б"', lesson:"text-vs-num",
      what:"склеивает строки. Число сначала превращают в строку через str()",
      code:'print("уровень " + str(7))' },
    { id:"str-mul", sig:'"-" * 10', lesson:"text-vs-num",
      what:"повторяет строку — так рисуют линии и полоски",
      code:'print("=" * 12)\nprint("#" * 3 + "." * 7)' },
    { id:"len", sig:"len(что-то)", lesson:"str-methods",
      what:"длина строки, списка, словаря — числом",
      code:'print(len("Кодоквест"), len([1, 2, 3]))' },
    { id:"upper", sig:".upper() и .lower()", lesson:"str-methods",
      what:"строка большими или маленькими буквами. Саму переменную не меняет",
      code:'имя = "Аня"\nprint(имя.upper(), имя.lower(), имя)' },
    { id:"strip", sig:".strip()", lesson:"str-methods",
      what:"убирает пробелы по краям — первое лекарство от «почему не совпало»",
      code:'print("[" + "  привет  ".strip() + "]")' },
    { id:"split", sig:".split(разделитель)", lesson:"str-methods",
      what:"режет строку на список. Без разделителя режет по пробелам",
      code:'print("кот бегемот ёж".split())\nprint("а,б,в".split(","))' },
    { id:"join", sig:'"разделитель".join(список)', lesson:"text-work",
      what:"склеивает список строк в одну строку. Обратное к split",
      code:'print(", ".join(["кот", "ёж", "сова"]))' },
    { id:"replace", sig:".replace(что, на что)", lesson:"str-methods",
      what:"меняет все вхождения. Возвращает новую строку, старую не трогает",
      code:'print("ту-ту-ту".replace("ту", "ды"))' },
    { id:"str-in", sig:'"а" in строка', lesson:"str-methods",
      what:"проверяет, есть ли кусок внутри строки",
      code:'print("код" in "кодоквест", "ёж" in "кодоквест")' },
    { id:"str-slice", sig:"строка[2:5]", lesson:"text-work",
      what:"кусок строки: с 2-го знака по 5-й, не включая 5-й",
      code:'с = "кодоквест"\nprint(с[0], с[:3], с[-4:])' },
    { id:"startswith", sig:".startswith() и .endswith()", lesson:"text-work",
      what:"проверяет начало и конец строки",
      code:'print("отчёт.txt".endswith(".txt"))' }
  ]
},
{
  group: "Числа",
  items: [
    { id:"div", sig:"/ и //", lesson:"math",
      what:"обычное деление всегда с точкой, // округляет ВНИЗ",
      code:'print(10 / 4)\nprint(10 // 4, -7 // 2)' },
    { id:"mod", sig:"%", lesson:"math",
      what:"остаток от деления. Чётность проверяют так: число % 2 == 0",
      code:'print(17 % 5, 10 % 2)' },
    { id:"pow", sig:"**", lesson:"math",
      what:"возведение в степень",
      code:'print(2 ** 10)' },
    { id:"int-str", sig:"int(), str(), float()", lesson:"text-vs-num",
      what:"превращает одно в другое. «2» и 2 — разные вещи",
      code:'print(int("7") + 1)\nprint(str(7) + "1")' },
    { id:"round", sig:"round(число, знаков)", lesson:"math",
      what:"округляет. Без второго числа — до целого",
      code:'print(round(3.14159, 2), round(2.5), round(3.5))' },
    { id:"abs", sig:"abs(число)", lesson:"math",
      what:"модуль: минус пропадает",
      code:'print(abs(-8), abs(8))' },
    { id:"minmax", sig:"min(), max(), sum()", lesson:"lists-first",
      what:"наименьшее, наибольшее и сумма списка",
      code:'очки = [7, 3, 9, 1]\nprint(min(очки), max(очки), sum(очки))' },
    { id:"mathmod", sig:"import math", lesson:"math-random",
      what:"корень, округление вверх и вниз, число пи",
      code:'import math\nprint(math.sqrt(144), math.ceil(2.1), math.floor(2.9))' }
  ]
},
{
  group: "Списки",
  items: [
    { id:"list-make", sig:"список = [1, 2, 3]", lesson:"lists-first",
      what:"много значений в одной коробке. Счёт начинается с нуля",
      code:'звери = ["кот", "ёж", "сова"]\nprint(звери[0], звери[-1])' },
    { id:"append", sig:".append(что-то)", lesson:"list-ops",
      what:"добавляет в конец списка",
      code:'с = [1, 2]\nс.append(3)\nprint(с)' },
    { id:"pop-remove", sig:".pop() и .remove(значение)", lesson:"list-ops",
      what:"pop убирает по номеру и отдаёт значение, remove — по значению",
      code:'с = ["кот", "ёж", "сова"]\nprint(с.pop(0))\nс.remove("сова")\nprint(с)' },
    { id:"list-slice", sig:"список[1:3]", lesson:"slices",
      what:"кусок списка. Копия списка целиком — это [:]",
      code:'ч = [0, 1, 2, 3, 4, 5]\nprint(ч[1:3], ч[:2], ч[::2], ч[::-1])' },
    { id:"sorted", sig:"sorted(список)", lesson:"sorting",
      what:"возвращает НОВЫЙ отсортированный список, старый не трогает",
      code:'ч = [3, 1, 2]\nprint(sorted(ч), sorted(ч, reverse=True), ч)' },
    { id:"sort-key", sig:"sorted(список, key=...)", lesson:"sorting",
      what:"сортировка по чему-то своему: по длине, по второму значению пары",
      code:'слова = ["ёж", "бегемот", "кот"]\nprint(sorted(слова, key=len))' },
    { id:"sort-inplace", sig:".sort() против sorted()", lesson:"sorting",
      what:".sort() меняет сам список и возвращает None, sorted() отдаёт новый",
      code:'очки = [3, 1, 2]\nновый = sorted(очки)\nprint(очки, новый)\nprint(очки.sort(), очки)' },
    { id:"slice-back", sig:"список[::-1]", lesson:"slices",
      what:"переворачивает список или строку: шаг -1 значит «читай с конца»",
      code:'print([1, 2, 3][::-1])\nprint("кодоквест"[::-1])' },
    { id:"list-in", sig:"значение in список", lesson:"lists-first",
      what:"проверяет, есть ли значение в списке",
      code:'print("ёж" in ["кот", "ёж"], 5 in [1, 2])' },
    { id:"index-count", sig:".index() и .count()", lesson:"list-ops",
      what:"на каком месте стоит и сколько раз встречается",
      code:'с = ["а", "б", "а"]\nprint(с.index("б"), с.count("а"))' },
    { id:"grid", sig:"поле[строка][столбец]", lesson:"grid",
      what:"список списков — сетка, карта, игровое поле",
      code:'поле = [[1, 2], [3, 4]]\nprint(поле[1][0])' },
    { id:"comp", sig:"[выражение for x in список]", lesson:"comp-basic",
      what:"новый список из старого одной строкой",
      code:'ч = [1, 2, 3]\nprint([x * x for x in ч])' },
    { id:"comp-if", sig:"[x for x in список if условие]", lesson:"comp-if",
      what:"то же самое, но с фильтром",
      code:'ч = [1, 2, 3, 4, 5, 6]\nprint([x for x in ч if x % 2 == 0])' }
  ]
},
{
  group: "Словари и множества",
  items: [
    { id:"dict-make", sig:"словарь = {ключ: значение}", lesson:"dict-first",
      what:"хранит пары. Ищет не по номеру, а по имени",
      code:'герой = {"имя": "Аня", "сила": 7}\nprint(герой["имя"])' },
    { id:"dict-set", sig:"словарь[ключ] = значение", lesson:"dict-first",
      what:"добавляет новую пару или меняет старую",
      code:'г = {"сила": 7}\nг["ловкость"] = 5\nг["сила"] = 8\nprint(г)' },
    { id:"dict-get", sig:".get(ключ, запасное)", lesson:"dict-first",
      what:"достаёт значение и не падает, если ключа нет",
      code:'г = {"сила": 7}\nprint(г.get("ум"), г.get("ум", 0))' },
    { id:"dict-in", sig:"ключ in словарь", lesson:"dict-first",
      what:"проверяет ключ ДО того, как к нему обратиться",
      code:'г = {"сила": 7}\nprint("сила" in г, "ум" in г)' },
    { id:"dict-items", sig:".items(), .keys(), .values()", lesson:"dict-loop",
      what:"перебор словаря: пары, только ключи, только значения",
      code:'г = {"сила": 7, "ум": 9}\nfor к, з in г.items():\n    print(к, з)\nprint(list(г.keys()), list(г.values()))' },
    { id:"dict-count", sig:"счётчик[ключ] = счётчик.get(ключ, 0) + 1", lesson:"dict-counter",
      what:"словарь-счётчик: считает повторы",
      code:'с = {}\nfor б in "мама":\n    с[б] = с.get(б, 0) + 1\nprint(с)' },
    { id:"comp-dict", sig:"{к: значение for к in ...}", lesson:"comp-dict",
      what:"строит словарь одной строкой",
      code:'ч = [1, 2, 3]\nprint({x: x * x for x in ч})' },
    { id:"set", sig:"set(список)", lesson:"sets",
      what:"множество: только уникальные, без порядка",
      code:'print(sorted(set([1, 2, 2, 3, 3, 3])))' },
    { id:"set-ops", sig:"| & -", lesson:"sets",
      what:"объединение, пересечение и разность множеств",
      code:'а = {1, 2, 3}\nб = {2, 3, 4}\nprint(sorted(а & б), sorted(а - б), sorted(а | б))' },
    { id:"set-add", sig:".add() и .discard()", lesson:"sets",
      what:"добавить и убрать. discard не ругается, если такого и не было",
      code:'звери = {"кот", "ёж"}\nзвери.add("лис")\nзвери.discard("кот")\nзвери.discard("кит")\nprint(sorted(звери))' },
    { id:"tuple", sig:"кортеж = (1, 2)", lesson:"tuples",
      what:"как список, но менять нельзя. Разбирают сразу в переменные",
      code:'точка = (3, 4)\nx, y = точка\nprint(x, y)' },
    { id:"counter", sig:"Counter(последовательность)", lesson:"collections",
      what:"готовый счётчик повторов с сортировкой по частоте",
      code:'from collections import Counter\nс = Counter("абракадабра")\nprint(с.most_common(2))' }
  ]
},
{
  group: "Условия и циклы",
  items: [
    { id:"if", sig:"if / elif / else", lesson:"if-else",
      what:"программа выбирает ветку. Двоеточие и отступ обязательны",
      code:'очки = 15\nif очки >= 24:\n    print("легенда")\nelif очки >= 10:\n    print("боец")\nelse:\n    print("новичок")' },
    { id:"compare", sig:"== != < > <= >=", lesson:"if-else",
      what:"сравнение. Одно равно присваивает, два — сравнивают",
      code:'print(3 == 3, 3 != 3, 2 <= 2)' },
    { id:"logic", sig:"and, or, not", lesson:"logic",
      what:"and — оба, or — хотя бы одно, not — наоборот",
      code:'возраст = 12\nprint(возраст > 10 and возраст < 15)\nprint(not возраст == 12)' },
    { id:"for-range", sig:"for i in range(n)", lesson:"for-range",
      what:"повторить n раз. Счёт с нуля, до n не включая",
      code:'for i in range(3):\n    print(i, "шаг")' },
    { id:"range-step", sig:"range(от, до, шаг)", lesson:"range-step",
      what:"считает через шаг и назад, если шаг отрицательный",
      code:'print(list(range(2, 11, 3)))\nprint(list(range(5, 0, -1)))' },
    { id:"for-list", sig:"for x in список", lesson:"lists-first",
      what:"перебирает сами значения, а не их номера",
      code:'for зверь in ["кот", "ёж"]:\n    print(зверь)' },
    { id:"enumerate", sig:"enumerate(список, 1)", lesson:"dict-loop",
      what:"даёт сразу номер и значение. Число в конце — с чего начать счёт",
      code:'for н, зверь in enumerate(["кот", "ёж"], 1):\n    print(н, зверь)' },
    { id:"zip", sig:"zip(a, b)", lesson:"tuples",
      what:"идёт по двум спискам сразу, парами",
      code:'for имя, очки in zip(["Аня", "Боря"], [7, 5]):\n    print(имя, очки)' },
    { id:"while", sig:"while условие", lesson:"while-loop",
      what:"повторяет, пока условие верно. Что-то внутри обязано его менять",
      code:'n = 3\nwhile n > 0:\n    print(n)\n    n -= 1' },
    { id:"break", sig:"break и continue", lesson:"break-cont",
      what:"break выходит из цикла совсем, continue пропускает один заход",
      code:'for x in range(6):\n    if x == 4:\n        break\n    if x % 2:\n        continue\n    print(x)' },
    { id:"nested", sig:"цикл внутри цикла", lesson:"for-nested",
      what:"строки и столбцы: внешний цикл — строка, внутренний — знаки в ней",
      code:'for с in range(3):\n    print("*" * (с + 1))' }
  ]
},
{
  group: "Функции",
  items: [
    { id:"def", sig:"def имя(параметры):", lesson:"functions",
      what:"своя команда. Объявляют выше того места, где зовут",
      code:'def привет(кто):\n    print("Привет,", кто)\n\n\nпривет("Аня")' },
    { id:"return", sig:"return значение", lesson:"fn-args",
      what:"отдаёт результат наружу. Без него функция возвращает None",
      code:'def площадь(ш, в):\n    return ш * в\n\n\nprint(площадь(3, 4))' },
    { id:"fn-multi", sig:"return a, b", lesson:"fn-multi",
      what:"возвращает несколько значений сразу — их принимают через запятую",
      code:'def края(с):\n    return min(с), max(с)\n\n\nниз, верх = края([4, 9, 1])\nprint(низ, верх)' },
    { id:"fn-default", sig:"def f(x, шаг=1)", lesson:"fn-default",
      what:"значение по умолчанию: параметр можно не передавать",
      code:'def плюс(x, шаг=1):\n    return x + шаг\n\n\nprint(плюс(5), плюс(5, 10))' },
    { id:"fn-varargs", sig:"*args и **kwargs", lesson:"fn-varargs",
      what:"любое число аргументов: args — списком, kwargs — словарём",
      code:'def сумма(*числа):\n    return sum(числа)\n\n\nprint(сумма(1, 2), сумма(1, 2, 3, 4))' },
    { id:"lambda", sig:"lambda x: выражение", lesson:"lambda",
      what:"функция без имени в одну строку. Чаще всего — как ключ сортировки",
      code:'пары = [("Аня", 7), ("Боря", 9)]\nprint(sorted(пары, key=lambda п: -п[1]))' },
    { id:"recursion", sig:"функция зовёт саму себя", lesson:"recursion",
      what:"обязательна ветка выхода, иначе не остановится",
      code:'def факториал(n):\n    if n <= 1:\n        return 1\n    return n * факториал(n - 1)\n\n\nprint(факториал(5))' },
    { id:"scope", sig:"переменная внутри функции", lesson:"scope",
      what:"живёт только внутри и наружу не выходит. Одинаковые имена не мешают",
      code:'ш = "снаружи"\n\n\ndef проба():\n    ш = "внутри"\n    print(ш)\n\n\nпроба()\nprint(ш)' },
    { id:"fn-dict", sig:"словарь функций", lesson:"fn-as-value",
      what:"действие выбирается по названию — короче длинной цепочки if. На этом стоит проект Мира 5",
      code:'действия = {\n    "плюс": lambda a, b: a + b,\n    "раз": lambda a, b: a * b,\n}\nвыбор = "плюс"\nprint(действия[выбор](2, 3), действия["раз"](2, 3))' },
    { id:"typing", sig:"def f(x: int) -> int", lesson:"typing",
      what:"подсказки типов: что принимаем и что отдаём. Python их не проверяет",
      code:'def сумма(числа: list, множитель: int = 2) -> int:\n    return sum(числа) * множитель\n\n\nprint(сумма([1, 2, 3]))' }
  ]
},
{
  group: "Классы",
  items: [
    { id:"class", sig:"class Имя:", lesson:"class-first",
      what:"чертёж вещи. По одному чертежу делают сколько угодно объектов",
      code:'class Герой:\n    def __init__(self, имя):\n        self.имя = имя\n\n\nprint(Герой("Аня").имя)' },
    { id:"init", sig:"def __init__(self, ...)", lesson:"class-init",
      what:"вызывается сам при создании. Значения запоминают через self",
      code:'class Точка:\n    def __init__(self, x, y):\n        self.x = x\n        self.y = y\n\n\nт = Точка(3, 4)\nprint(т.x, т.y)' },
    { id:"method", sig:"метод объекта", lesson:"class-methods",
      what:"функция внутри класса. Первым параметром всегда self",
      code:'class Счёт:\n    def __init__(self):\n        self.n = 0\n\n    def плюс(self):\n        self.n += 1\n\n\nс = Счёт()\nс.плюс()\nс.плюс()\nprint(с.n)' },
    { id:"repr", sig:"def __repr__(self)", lesson:"class-init",
      what:"как объект выглядит при печати. Без него видно только адрес в памяти",
      code:'class Кот:\n    def __repr__(self):\n        return "Кот()"\n\n\nprint([Кот(), Кот()])' },
    { id:"inherit", sig:"class Наследник(Родитель)", lesson:"inherit",
      what:"берёт всё у родителя и добавляет своё",
      code:'class Зверь:\n    def голос(self):\n        return "..."\n\n\nclass Кот(Зверь):\n    def голос(self):\n        return "мяу"\n\n\nprint(Зверь().голос(), Кот().голос())' },
    { id:"super", sig:"super().метод()", lesson:"inherit",
      what:"зовёт родительскую версию, чтобы не переписывать её заново",
      code:'class Вещь:\n    def __init__(self, имя):\n        self.имя = имя\n\n\nclass Меч(Вещь):\n    def __init__(self, имя, урон):\n        super().__init__(имя)\n        self.урон = урон\n\n\nм = Меч("Меч", 7)\nprint(м.имя, м.урон)' }
  ]
},
{
  group: "Ошибки и проверки",
  items: [
    { id:"try", sig:"try / except", lesson:"try-except",
      what:"ловит ошибку, чтобы программа не падала целиком",
      code:'try:\n    print(10 // 0)\nexcept ZeroDivisionError:\n    print("на ноль делить нельзя")' },
    { id:"except-as", sig:"except Ошибка as e", lesson:"try-except",
      what:"даёт доступ к самому сообщению об ошибке",
      code:'try:\n    int("ёж")\nexcept ValueError as e:\n    print("не вышло:", type(e).__name__)' },
    { id:"finally", sig:"finally", lesson:"try-except",
      what:"выполнится в любом случае — и когда ошибка была, и когда нет",
      code:'try:\n    print(10 // 0)\nexcept ZeroDivisionError:\n    print("поймали")\nfinally:\n    print("а это всегда")' },
    { id:"raise", sig:"raise ValueError(текст)", lesson:"raise",
      what:"сообщает о проблеме самому. Текст пиши так, чтобы было понятно",
      code:'def корень(x):\n    if x < 0:\n        raise ValueError("отрицательное")\n    return x ** 0.5\n\n\ntry:\n    корень(-1)\nexcept ValueError as e:\n    print("поймали:", e)' },
    { id:"assert", sig:"assert условие, сообщение", lesson:"assert",
      what:"проверка «так и должно быть». Молчит, пока всё верно",
      code:'def удвой(x):\n    return x * 2\n\n\nassert удвой(3) == 6\nprint("проверка прошла")' },
    { id:"none", sig:"None и is None", lesson:"fn-args",
      what:"«ничего». Сравнивают через is, а не через ==",
      code:'def найти(с, что):\n    for x in с:\n        if x == что:\n            return x\n    return None\n\n\nprint(найти([1, 2], 9) is None)' },
    { id:"type", sig:"type(значение)", lesson:"text-vs-num",
      what:"что это вообще такое. Первое, что смотрят при странной ошибке",
      code:'print(type(7).__name__, type("7").__name__, type([]).__name__)' },
    { id:"with-own", sig:"__enter__ и __exit__", lesson:"context",
      what:"свой with: __enter__ на входе, __exit__ на выходе — даже если внутри ошибка",
      code:'class Скобки:\n    def __enter__(self):\n        print("[")\n        return self\n\n    def __exit__(self, *a):\n        print("]")\n\n\nwith Скобки():\n    print("внутри")' }
  ]
},
{
  group: "Модули и данные",
  items: [
    { id:"import", sig:"import модуль", lesson:"imports",
      what:"подключает чужой код. Дальше зовут через точку",
      code:'import math\nprint(math.pi)' },
    { id:"from-import", sig:"from модуль import имя", lesson:"imports",
      what:"берёт из модуля одну вещь, чтобы писать её без точки",
      code:'from math import sqrt\nprint(sqrt(81))' },
    { id:"random", sig:"random.randint(a, b)", lesson:"random",
      what:"случайное целое от a до b включительно. Каждый запуск разное",
      code:'import random\nprint(random.randint(1, 6) in range(1, 7))' },
    { id:"choice", sig:"random.choice(список)", lesson:"random",
      what:"случайный элемент списка",
      code:'import random\nзвери = ["кот", "ёж"]\nprint(random.choice(звери) in звери)' },
    { id:"json", sig:"json.dumps(данные)", lesson:"json",
      what:"превращает словарь в текст. Для русских букв нужен ensure_ascii=False",
      code:'import json\nprint(json.dumps({"имя": "Аня"}, ensure_ascii=False))' },
    { id:"json-loads", sig:"json.loads(текст)", lesson:"json",
      what:"обратно: из текста в словарь",
      code:'import json\nд = json.loads(\'{"сила": 7}\')\nprint(д["сила"] + 1)' },
    { id:"regex", sig:"re.findall(шаблон, текст)", lesson:"regex",
      what:"ищет по шаблону. \\d цифра, \\w буква, + один и больше",
      code:'import re\nprint(re.findall(r"\\d+", "аня 7, боря 12"))' },
    { id:"re-sub", sig:"re.sub(шаблон, на что, текст)", lesson:"regex",
      what:"замена по шаблону — так вычищают мусор",
      code:'import re\nprint(re.sub(r"\\s+", " ", "много    пробелов"))' },
    { id:"generator", sig:"yield", lesson:"generators",
      what:"отдаёт значения по одному, а не списком сразу",
      code:'def первые(n):\n    for i in range(n):\n        yield i * i\n\n\nprint(list(первые(4)))' },
    { id:"decorator", sig:"@декоратор", lesson:"decorators",
      what:"обёртка вокруг функции: что-то делает до и после неё",
      code:'def громко(ф):\n    def обёртка(*a):\n        return ф(*a).upper()\n    return обёртка\n\n\n@громко\ndef привет():\n    return "привет"\n\n\nprint(привет())' },
    { id:"date", sig:"date(год, месяц, день)", lesson:"datetime",
      what:"дата как значение. У неё есть .year, .month, .day",
      code:'from datetime import date\nд = date(2026, 3, 8)\nprint(д, д.year, д.day)' },
    { id:"date-math", sig:"дата2 - дата1 и timedelta", lesson:"datetime",
      what:"разность дат даёт дни, timedelta сдвигает дату вперёд и назад",
      code:'from datetime import date, timedelta\nначало = date(2026, 3, 8)\nконец = date(2026, 9, 1)\nprint((конец - начало).days)\nprint(начало + timedelta(days=10))' },
    { id:"strftime", sig:'.strftime("%d.%m.%Y")', lesson:"datetime",
      what:"дата в привычном виде. %d день, %m месяц, %Y год",
      code:'from datetime import date\nprint(date(2026, 3, 8).strftime("%d.%m.%Y"))' },
    { id:"defaultdict", sig:"defaultdict(list)", lesson:"collections",
      what:"словарь, который сам заводит пустое значение для нового ключа",
      code:'from collections import defaultdict\nпо_букве = defaultdict(list)\nfor слово in ["кот", "ёж", "кит"]:\n    по_букве[слово[0]].append(слово)\nprint(dict(по_букве))' },
    { id:"combinations", sig:"itertools.combinations(что, по сколько)", lesson:"itertools",
      what:"все сочетания без повторов: порядок внутри пары не важен",
      code:'import itertools\nprint(list(itertools.combinations(["кот", "ёж", "кит"], 2)))' },
    { id:"product", sig:"itertools.product(a, b)", lesson:"itertools",
      what:"все пары из двух наборов — вложенный цикл одной строкой",
      code:'import itertools\nfor буква, число in itertools.product("кс", [1, 2]):\n    print(буква, число)' },
    { id:"open-read", sig:'with open(имя, encoding="utf-8")', lesson:"files-read",
      what:'читает файл построчно. Без encoding="utf-8" русские буквы поедут',
      data:{ "звери.txt": "кот\nёж\nкит\n" },
      code:'with open("звери.txt", encoding="utf-8") as f:\n    for строка in f:\n        print(строка.strip())' },
    { id:"open-write", sig:'open(имя, "w", encoding="utf-8")', lesson:"files-write",
      what:'«w» стирает файл и пишет заново, «a» дописывает в конец. Перенос строки пиши сам',
      code:'with open("итог.txt", "w", encoding="utf-8") as f:\n    f.write("первая\\n")\n    f.write("вторая\\n")\n\nwith open("итог.txt", encoding="utf-8") as f:\n    print(f.read().strip())' },
    { id:"csv", sig:"csv.DictReader(файл)", lesson:"csv",
      what:'таблица строками-словарями, ключи — названия столбцов. Для csv нужен ещё newline=""',
      data:{ "оценки.csv": "имя,балл\nАня,9\nБоря,7\n" },
      code:'import csv\nwith open("оценки.csv", encoding="utf-8", newline="") as f:\n    for строка in csv.DictReader(f):\n        print(строка["имя"], строка["балл"])' },
    { id:"pathlib", sig:'Path("папка") / "файл"', lesson:"pathlib",
      what:"путь собирают косой чертой, а не склейкой строк",
      code:'from pathlib import Path\nп = Path("данные") / "отчёт.txt"\nprint(п)\nprint(п.name, п.suffix)' }
  ]
}
];
